#OPCIONES
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'opciones.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class OpcionesWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)
        self.setup_connections()

    def setup_connections(self):
        self.ui.Button_agregar.clicked.connect(self.show_agregar)
        self.ui.Button_verlista.clicked.connect(self.show_lista)
        self.ui.Button_salir.clicked.connect(self.logout)

    def show_agregar(self):
        from ventana_agregarcontraseña import AgregarWindow
        self.hide()
        self.agregar_window = AgregarWindow()
        self.agregar_window.show()

    def show_lista(self):
        from ventana_listacontraseñas import ListaWindow
        self.hide()
        self.lista_window = ListaWindow()
        self.lista_window.show()

    def logout(self):
        self.hide()
        from src.login import LoginWindow
        self.login_window = LoginWindow()
        self.login_window.show()


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(586, 479)
        MainWindow.setStyleSheet("QWidget#centralwidget{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(76, 76, 230, 255), stop:1 rgba(255, 255, 255, 255));}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 801, 641))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("b45e8435763d98ad1ed44ff627b67137.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.WELCOME = QtWidgets.QLabel(self.centralwidget)
        self.WELCOME.setGeometry(QtCore.QRect(160, 40, 271, 91))
        self.WELCOME.setStyleSheet("font: 75 28pt \"Calisto MT\";\n"
"color: rgb(255, 255, 255);")
        self.WELCOME.setScaledContents(True)
        self.WELCOME.setObjectName("WELCOME")
        self.lbl_opcion = QtWidgets.QLabel(self.centralwidget)
        self.lbl_opcion.setGeometry(QtCore.QRect(140, 130, 241, 61))
        self.lbl_opcion.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 22pt \"Sitka\";")
        self.lbl_opcion.setObjectName("lbl_opcion")
        self.lb_fondo = QtWidgets.QLabel(self.centralwidget)
        self.lb_fondo.setGeometry(QtCore.QRect(30, 220, 221, 211))
        self.lb_fondo.setStyleSheet("\n"
"\n"
"border-radius: 30px; /* Cambia 10px por el radio deseado */")
        self.lb_fondo.setText("")
        self.lb_fondo.setPixmap(QtGui.QPixmap("pngtree-security-icon-png-image_8700464.png"))
        self.lb_fondo.setScaledContents(True)
        self.lb_fondo.setObjectName("lb_fondo")
        self.Button_agregar = QtWidgets.QPushButton(self.centralwidget)
        self.Button_agregar.setGeometry(QtCore.QRect(320, 230, 221, 51))
        self.Button_agregar.setStyleSheet("background-color: rgb(73, 194, 101);\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"border-radius:20px;")
        self.Button_agregar.setObjectName("Button_agregar")
        self.Button_verlista = QtWidgets.QPushButton(self.centralwidget)
        self.Button_verlista.setGeometry(QtCore.QRect(350, 300, 131, 51))
        self.Button_verlista.setStyleSheet("background-color: rgb(73, 194, 101);\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"border-radius:20px;")
        self.Button_verlista.setObjectName("Button_verlista")
        self.Button_salir = QtWidgets.QPushButton(self.centralwidget)
        self.Button_salir.setGeometry(QtCore.QRect(350, 370, 141, 41))
        self.Button_salir.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"border-radius:20px;")
        self.Button_salir.setObjectName("Button_salir")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.WELCOME.setText(_translate("MainWindow", "BIENVENIDO "))
        self.lbl_opcion.setText(_translate("MainWindow", "Elija un opcion"))
        self.Button_agregar.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.Button_agregar.setText(_translate("MainWindow", "AGREGAR CONTRASEÑA "))
        self.Button_verlista.setText(_translate("MainWindow", "VER LISTA "))
        self.Button_salir.setText(_translate("MainWindow", "SALIR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
